# Generated by Django 5.0 on 2023-12-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='football_players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('matches_played', models.IntegerField()),
                ('total_goals', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
